<?php

function catalog_menu_block_info(){
	$blocks = array();
  $blocks['catalog_menu'] = array(
    'info' => t('Умное меню каталога'),
    //'cache' => DRUPAL_NO_CACHE,
  );
  
  return $blocks;

}

function catalog_menu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'catalog_menu':
	$block['subject'] = t('Умное меню каталога');
      $block['content'] = "<div>Умное меню каталога</div>";/*theme('kpzhilie_filter_blocktemplate', array());*/
      break;
  }
  return $block;
}

